export const SELECT_SUBFOL_APP_ICONS = "SELECT_SUBFOL_APP_ICONS";
export const GET_LIST_FILE = "GET_LIST_FILE";
export const GET_LIST_FILE_SUCCESS = "GET_LIST_FILE_SUCCESS";
export const GET_LIST_FILE_FAIL = "GET_LIST_FILE_FAIL";
