// export const SELECT_SUBFOL_APP_ICONS = "SELECT_SUBFOL_APP_ICONS";s
export const GET_LIST_FILE = "GET_LIST_FILE";
export const GET_LIST_FILE_SUCCESS = "GET_LIST_FILE_SUCCESS";
export const GET_LIST_FILE_FAIL = "GET_LIST_FILE_FAIL";

export const GET_NEW_LIST_FILE = "GET_NEW_LIST_FILE";
export const GET_NEW_LIST_FILE_SUCCESS = "GET_NEW_LIST_FILE_SUCCESS";
export const GET_NEW_LIST_FILE_FAIL = "GET_NEW_LIST_FILE_FAIL";

export const GET_SUBFOL_LIST = "GET_SUBFOL_LIST";
export const GET_SUBFOL_LIST_SUCCESS = "GET_SUBFOL_LIST_SUCCESS";
export const GET_SUBFOL_LIST_FAIL = "GET_SUBFOL_LIST_FAIL";
